version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
    - '1010:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: hermes_db
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/1.sql
