name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18.14.0]
      fail-fast: false

    name: "CI/CD check. Node: ${{ matrix.node_version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"
          cache-dependency-path: 'package-lock.json'

      - name: Install deps
        run: npm install --no-frozen-lockfile

      - name: Test unit
        run: npm run test:unit

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

  check-commit-message:
    name: check commit message
    runs-on: ubuntu-latest
    steps:
    - uses: gsactions/commit-message-checker@v2
      with:
        pattern: '(?:build|docs|refactor|test|fix|perf|chore|feat|ci)(?:\(\w+\))?:\s[a-z]{1,2}.+'
        error: "The commit message must follow the commit messages guidelines"
        excludeDescription: 'true'
        excludeTitle: 'true'
        checkAllCommitMessages: 'true'
        accessToken: ${{ secrets.GITHUB_TOKEN }}

  branches-convention:
    name: "Conventional Branch Names"
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z])+'
          allowed_prefixes: 'feature,stable,fix,chore,doc,feat,build,ci'
          ignore: main,develop
          min_length: 4
          max_length: 30
