name: ci

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  verify-semantic-pull-request:
    uses: ./.github/workflows/semantic_pull_request.yml
    with:
      scopes: "dart_package, deps, flutter_package, pana, semantic_pull_request, spell_check"

  build:
    needs:
      [
        verify-semantic-pull-request,
      ]

    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'
