name: CI

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18.14.0]
      fail-fast: false

    name: "Lint, Format and Test node-${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@cf4fe8759a45edd76ed6215da3529d2dbd2a3c68
        with:
          files: |
            docs/**
            .github/**
            !.github/workflows/ci.yml
            packages/create-vite/template**
            **.md

      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"
          cache-dependency-path: 'package-lock.json'

      - name: Install deps
        run: npm install --no-frozen-lockfile

      - name: Test unit
        run: npm run test:unit

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Convetional Commits
        uses: webiny/action-conventional-commits@v1.1.0
